### ISSUE TITLE
Issue with :GoModCheck

### ISSUE THREAD

**Issue by ellisonleao** [WhoIsSethDaniel/goldsmith.nvim#5]
Hey @WhoIsSethDaniel thanks for the awesome plugin, really hope to be able to contribute to it soon. I am having an issue with `:GoModCheck` command here, not sure if it's something in my configuration or any missing items to be installed. The error is:

```
E5108: Error executing lua ...packer/start/goldsmith.nvim/lua/goldsmith/treesitter.lua:84: attempt to index a nil va
lue
stack traceback:
        ...packer/start/goldsmith.nvim/lua/goldsmith/treesitter.lua:84: in function 'get_all_modules'
        ...e/pack/packer/start/goldsmith.nvim/lua/goldsmith/mod.lua:9: in function 'check_for_upgrades'
        [string ":lua"]:1: in main chunk
```

From what i could see, it's something related to treesitter not being able to get the correct parser. Any Thoughts?

**Comment by WhoIsSethDaniel** [comment]
FWIW, I'm unable to replicate this problem with my setup. 

What does `:echo &ft` report when you are editing the file where this happens? My guess is the filetype is fine since the `:GoModCheck` command is available (and should only be available when you are editing a file with the appropriate filetype).

Make certain you have the `gomod` parser installed for `nvim-treesitter`.  Run `:checkhealth nvim-treesitter` and see if `gomod` shows up as a parser and no errors reported for it at the bottom of the report.  You might try running `:TSInstall gomod`. If it says it's already installed, tell it to install it again.

What version of `nvim-treesitter` are you using?  If you can go to where your `nvim-treesitter` is installed and run `git rev-parse HEAD` and let me know what that command returns.

What does your `go.mod` look like?  Can you post it here? Considering how quickly treesitter fails I doubt it's the `go.mod` that's the problem. This seems like a setup issue.

**Comment by WhoIsSethDaniel** [comment]
Okay, I can replicate this problem *iff* I have removed the `gomod` parser.  So it seems almost certain that you are missing the `gomod` parser from your `nvim-treesitter` installation.

**Comment by ellisonleao** [comment]
hey @WhoIsSethDaniel, yeah I did the fix by installing gomod parser. Are you interested in a PR to add a treesitter check for required parsers?

**Comment by WhoIsSethDaniel** [comment]
Sure, I'd be interested in that

**Comment by WhoIsSethDaniel** [comment]
If you have any questions you can ask them here or in the discussion area. https://github.com/WhoIsSethDaniel/goldsmith.nvim/discussions
